### ISSUE TITLE
Support discuz or duoshuo?

### ISSUE THREAD

**Issue by lucasjinreal** [levblanc/hexo-theme-aero-dual#9] opened 2017-04-06 13:02 UTC
Aero dual is pretty nice looks, but if have original blog comment support would be better? Is there already have or should be add these feature in?

**Comment by levblanc** [comment] 2017-04-11 02:20
Considering this as a duplicate of issuse #7 , please refer to it for more info.

**Closed as completed by levblanc** 2017-04-11 02:20 UTC
